services:
  luxJob_API:
    image: my-api:latest
    container_name: luxJob-API_app_container
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "./app/:/api_server"
    env_file:
      - .Renviron